// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: showmeat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing a string with meat names and amounts.
type MeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeatList string `protobuf:"bytes,1,opt,name=meat_list,json=meatList,proto3" json:"meat_list,omitempty"`
}

func (x *MeatRequest) Reset() {
	*x = MeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_showmeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeatRequest) ProtoMessage() {}

func (x *MeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_showmeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeatRequest.ProtoReflect.Descriptor instead.
func (*MeatRequest) Descriptor() ([]byte, []int) {
	return file_showmeat_proto_rawDescGZIP(), []int{0}
}

func (x *MeatRequest) GetMeatList() string {
	if x != nil {
		return x.MeatList
	}
	return ""
}

// The response message containing the list of meats with their amounts.
type MeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeatItems map[string]int32 `protobuf:"bytes,1,rep,name=meat_items,json=meatItems,proto3" json:"meat_items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *MeatResponse) Reset() {
	*x = MeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_showmeat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeatResponse) ProtoMessage() {}

func (x *MeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_showmeat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeatResponse.ProtoReflect.Descriptor instead.
func (*MeatResponse) Descriptor() ([]byte, []int) {
	return file_showmeat_proto_rawDescGZIP(), []int{1}
}

func (x *MeatResponse) GetMeatItems() map[string]int32 {
	if x != nil {
		return x.MeatItems
	}
	return nil
}

var File_showmeat_proto protoreflect.FileDescriptor

var file_showmeat_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x77, 0x6d, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x65, 0x61, 0x74, 0x22, 0x2a, 0x0a, 0x0b, 0x4d, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x61, 0x74, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x61, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x0c, 0x4d, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x6d, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x61, 0x74, 0x2e, 0x4d,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x61, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x6d, 0x65, 0x61, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x3c, 0x0a, 0x0e, 0x4d, 0x65, 0x61, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x32, 0x46, 0x0a, 0x0b, 0x4d, 0x65, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x74, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x12, 0x11, 0x2e, 0x6d, 0x65, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x65, 0x61, 0x74, 0x2e, 0x4d,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x67,
	0x6f, 0x66, 0x6f, 0x72, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_showmeat_proto_rawDescOnce sync.Once
	file_showmeat_proto_rawDescData = file_showmeat_proto_rawDesc
)

func file_showmeat_proto_rawDescGZIP() []byte {
	file_showmeat_proto_rawDescOnce.Do(func() {
		file_showmeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_showmeat_proto_rawDescData)
	})
	return file_showmeat_proto_rawDescData
}

var file_showmeat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_showmeat_proto_goTypes = []any{
	(*MeatRequest)(nil),  // 0: meat.MeatRequest
	(*MeatResponse)(nil), // 1: meat.MeatResponse
	nil,                  // 2: meat.MeatResponse.MeatItemsEntry
}
var file_showmeat_proto_depIdxs = []int32{
	2, // 0: meat.MeatResponse.meat_items:type_name -> meat.MeatResponse.MeatItemsEntry
	0, // 1: meat.MeatService.GetMeatAmounts:input_type -> meat.MeatRequest
	1, // 2: meat.MeatService.GetMeatAmounts:output_type -> meat.MeatResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_showmeat_proto_init() }
func file_showmeat_proto_init() {
	if File_showmeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_showmeat_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_showmeat_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_showmeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_showmeat_proto_goTypes,
		DependencyIndexes: file_showmeat_proto_depIdxs,
		MessageInfos:      file_showmeat_proto_msgTypes,
	}.Build()
	File_showmeat_proto = out.File
	file_showmeat_proto_rawDesc = nil
	file_showmeat_proto_goTypes = nil
	file_showmeat_proto_depIdxs = nil
}
